[package]
name = "tsverify"
description = "Compare alignments produced by tsalign"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
license = "BSD-2-Clause"
repository = "https://github.com/ISibboI/template-switch-verifier.git"
version = "0.0.0"
edition = "2021"

[dependencies]
lib_tsalign = { version = "0.4.1", features = ["serde"] }
serde = { version = "1.0.213", features = ["derive"] }
serde-value = "0.7.0"
toml = "0.8.19"
clap = { version = "4.5.20", features = ["derive"] }
log = "0.4.22"
simplelog = "0.12.2"
